const customerData = [
  {
    account_id: 1,
    address1: null,
    address2: null,
    area: "Thiruvanmiyur",
    city: "Chennai",
    communication_channel: null,
    country: "India",
    customer_id: 1,
    customer_name: "Madhusudhan",
    dob: "01-05-1996",
    email: null,
    gender: "M",
    last_visited_date: "2024-03-31",
    last_visited_store: {
      store_id: 47,
      store_name: "Blr Brewing Co -Kanakapura Rd",
    },
    last_spent_amount: 6350,
    mobile_number: "9845367291",
    occupation: null,
    top_visited_store: {
      store_id: 47,
      store_name: "Blr Brewing Co -Kanakapura Rd",
    },
    total_spent: 43400,
    visits_count: 5,
    whatsapp_number: "9845367291",
  },
  {
    account_id: 1,
    address1: null,
    address2: null,
    area: "TNagar",
    city: "Chennai",
    communication_channel: null,
    country: "India",
    customer_id: 2,
    customer_name: "Ronojeet",
    dob: "24-08-1993",
    email: null,
    gender: "M",
    last_visited_date: "2023-12-22",
    last_visited_store: {
      store_id: 210,
      store_name: "BLR Brewing Co. - HSR Layout",
    },
    last_spent_amount: 51700,
    mobile_number: "7348923337",
    occupation: null,
    top_visited_store: {
      store_id: 210,
      store_name: "BLR Brewing Co. - HSR Layout",
    },
    total_spent: 51700,
    visits_count: 1,
    whatsapp_number: "7348923337",
  },
  {
    account_id: 1,
    address1: null,
    address2: null,
    area: "Ashok nagar",
    city: "Chennai",
    communication_channel: null,
    country: "India",
    customer_id: 3,
    customer_name: "Aryan",
    dob: "01-01-2003",
    email: null,
    gender: "M",
    last_visited_date: "2021-11-22",
    last_visited_store: {
      store_id: 210,
      store_name: "BLR Brewing Co. - HSR Layout",
    },
    last_spent_amount: 154000,
    mobile_number: "7754884368",
    occupation: null,
    top_visited_store: {
      store_id: 210,
      store_name: "BLR Brewing Co. - HSR Layout",
    },
    total_spent: 185000,
    visits_count: 2,
    whatsapp_number: "7754884368",
  },
  {
    account_id: 1,
    address1: null,
    address2: null,
    area: "Madipakkam",
    city: "Chennai",
    communication_channel: null,
    country: null,
    customer_id: 4,
    customer_name: "Manish",
    dob: "02-02-1986",
    email: null,
    gender: "M",
    last_visited_date: "2021-07-25",
    last_visited_store: {
      store_id: 210,
      store_name: "BLR Brewing Co. - HSR Layout",
    },
    last_spent_amount: 12600,
    mobile_number: "8810671408",
    occupation: null,
    top_visited_store: {
      store_id: 210,
      store_name: "BLR Brewing Co. - HSR Layout",
    },
    total_spent: 47000,
    visits_count: 2,
    whatsapp_number: "8810671408",
  },
  {
    account_id: 1,
    address1: null,
    address2: null,
    area: "Parrys",
    city: "Chennai",
    communication_channel: null,
    country: "India",
    customer_id: 5,
    customer_name: "Rathan",
    dob: "06-08-2000",
    email: null,
    gender: "M",
    last_visited_date: "2024-02-25",
    last_visited_store: {
      store_id: 210,
      store_name: "BLR Brewing Co. - HSR Layout",
    },
    last_spent_amount: 162000,
    mobile_number: "9483344528",
    occupation: null,
    top_visited_store: {
      store_id: 210,
      store_name: "BLR Brewing Co. - HSR Layout",
    },
    total_spent: 162000,
    visits_count: 1,
    whatsapp_number: "9483344528",
  },
  {
    account_id: 1,
    address1: null,
    address2: null,
    area: "Perungudi",
    city: "Chennai",
    communication_channel: null,
    country: "India",
    customer_id: 6,
    customer_name: "Jason",
    dob: "03-04-2004",
    email: null,
    gender: "M",
    last_visited_date: "2023-04-03",
    last_visited_store: {
      store_id: 210,
      store_name: "BLR Brewing Co. - HSR Layout",
    },
    last_spent_amount: 45960,
    mobile_number: "9880681792",
    occupation: null,
    top_visited_store: {
      store_id: 210,
      store_name: "BLR Brewing Co. - HSR Layout",
    },
    total_spent: 274000,
    visits_count: 8,
    whatsapp_number: "9880681792",
  },
  {
    account_id: 1,
    address1: null,
    address2: null,
    area: "Red hills",
    city: "Chennai",
    communication_channel: null,
    country: "India",
    customer_id: 7,
    customer_name: "Arjun",
    dob: "15-05-1978",
    email: null,
    gender: "M",
    last_visited_date: "2022-10-01",
    last_visited_store: {
      store_id: 210,
      store_name: "BLR Brewing Co. - HSR Layout",
    },
    last_spent_amount: 12000,
    mobile_number: "8050764016",
    occupation: null,
    top_visited_store: {
      store_id: 210,
      store_name: "BLR Brewing Co. - HSR Layout",
    },
    total_spent: 124000,
    visits_count: 3,
    whatsapp_number: "8050764016",
  },
  {
    account_id: 1,
    address1: null,
    address2: null,
    area: "Viruthasalam",
    city: "Cuddalore",
    communication_channel: null,
    country: "India",
    customer_id: 8,
    customer_name: "Satish",
    dob: "18-09-1999",
    email: null,
    gender: "M",
    last_visited_date: "2023-10-01",
    last_visited_store: {
      store_id: 210,
      store_name: "BLR Brewing Co. - HSR Layout",
    },
    last_spent_amount: 32710,
    mobile_number: "8217457422",
    occupation: null,
    top_visited_store: {
      store_id: 210,
      store_name: "BLR Brewing Co. - HSR Layout",
    },
    total_spent: 327000,
    visits_count: 4,
    whatsapp_number: "8217457422",
  },
  {
    account_id: 1,
    address1: null,
    address2: null,
    area: "Thiruvanmiyur",
    city: "Chennai",
    communication_channel: null,
    country: "India",
    customer_id: 9,
    customer_name: "Shruti",
    dob: "05-05-1997",
    email: null,
    gender: "F",
    last_visited_date: "2024-04-04",
    last_visited_store: {
      store_id: 210,
      store_name: "BLR Brewing Co. - HSR Layout",
    },
    last_spent_amount: 7500,
    mobile_number: "7845181903",
    occupation: null,
    top_visited_store: {
      store_id: 210,
      store_name: "BLR Brewing Co. - HSR Layout",
    },
    total_spent: 57000,
    visits_count: 3,
    whatsapp_number: "7845181903",
  },
  {
    account_id: 1,
    address1: null,
    address2: null,
    area: null,
    city: null,
    communication_channel: null,
    country: "Dubai",
    customer_id: 10,
    customer_name: "Roshini",
    dob: "29-02-2001",
    email: null,
    gender: "F",
    last_visited_date: "2023-10-24",
    last_visited_store: {
      store_id: 210,
      store_name: "BLR Brewing Co. - HSR Layout",
    },
    last_spent_amount: 241300,
    mobile_number: "9663824488",
    occupation: null,
    top_visited_store: {
      store_id: 210,
      store_name: "BLR Brewing Co. - HSR Layout",
    },
    total_spent: 241300,
    visits_count: 1,
    whatsapp_number: "9663824488",
  },
];

module.exports = customerData;
