const customerData = [
  {
    account_id: 32,
    address1: null,
    address2: null,
    area: null,
    city: null,
    communication_channel: null,
    country: null,
    customer_id: 395560,
    customer_name: "anil",
    dob: null,
    email: null,
    gender: "male",
    created_at: "2024-01-07",
    last_visited_date: "2024-02-11",
    last_visited_store: {
      store_id: 47,
      store_name: "Blr Brewing Co -Kanakapura Rd",
    },
    last_spent_amount: 49000,
    mobile_number: "8050883862",
    occupation: null,
    top_visited_store: {
      store_id: 47,
      store_name: "Blr Brewing Co -Kanakapura Rd",
    },
    total_spent: 330500,
    visits_count: 3,
    whatsapp_number: "8050883862",
    total_loyalty_points: 4005
  },
  {
    account_id: 32,
    address1: null,
    address2: null,
    area: null,
    city: null,
    communication_channel: null,
    country: null,
    customer_id: 396591,
    customer_name: "Hari",
    dob: null,
    email: null,
    gender: "male",
    created_at: "2023-12-27",
    last_visited_date: "2024-02-01",
    last_visited_store: {
      store_id: 47,
      store_name: "Blr Brewing Co -Kanakapura Rd",
    },
    last_spent_amount: 393900,
    mobile_number: "7259827204",
    occupation: null,
    top_visited_store: {
      store_id: 47,
      store_name: "Blr Brewing Co -Kanakapura Rd",
    },
    total_spent: 542400,
    visits_count: 2,
    whatsapp_number: "7259827204",
    total_loyalty_points: 5424
  },
  {
    account_id: 32,
    address1: null,
    address2: null,
    area: null,
    city: null,
    communication_channel: null,
    country: null,
    customer_id: 397711,
    customer_name: "Kalyan Kumar",
    dob: null,
    email: null,
    gender: "male",
    created_at: "2023-12-04",
    last_visited_date: "2023-12-21",
    last_visited_store: {
      store_id: 47,
      store_name: "Blr Brewing Co -Kanakapura Rd",
    },
    last_spent_amount: 281000,
    mobile_number: "9845572852",
    occupation: null,
    top_visited_store: {
      store_id: 47,
      store_name: "Blr Brewing Co -Kanakapura Rd",
    },
    total_spent: 499000,
    visits_count: 2,
    whatsapp_number: "9845572852",
    total_loyalty_points: 4990
  },
  {
    account_id: 32,
    address1: null,
    address2: null,
    area: null,
    city: null,
    communication_channel: null,
    country: null,
    customer_id: 400858,
    customer_name: "Nisha",
    dob: null,
    email: null,
    gender: "female",
    created_at: "2024-01-01",
    last_visited_date: "2024-01-24",
    last_visited_store: {
      store_id: 47,
      store_name: "Blr Brewing Co -Kanakapura Rd",
    },
    last_spent_amount: 183500,
    mobile_number: "9972946803",
    occupation: null,
    top_visited_store: {
      store_id: 47,
      store_name: "Blr Brewing Co -Kanakapura Rd",
    },
    total_spent: 537400,
    visits_count: 2,
    whatsapp_number: "9972946803",
    total_loyalty_points: 5374
  },
  {
    account_id: 32,
    address1: null,
    address2: null,
    area: null,
    city: null,
    communication_channel: null,
    country: null,
    customer_id: 401318,
    customer_name: "Vinod",
    dob: null,
    email: null,
    gender: "male",
    created_at: "2023-12-10",
    last_visited_date: "2024-01-20",
    last_visited_store: {
      store_id: 47,
      store_name: "Blr Brewing Co -Kanakapura Rd",
    },
    last_spent_amount: 297000,
    mobile_number: "9964304000",
    occupation: null,
    top_visited_store: {
      store_id: 47,
      store_name: "Blr Brewing Co -Kanakapura Rd",
    },
    total_spent: 1163000,
    visits_count: 4,
    whatsapp_number: "9964304000",
    total_loyalty_points: 11630
  },
  {
    account_id: 32,
    address1: null,
    address2: null,
    area: null,
    city: null,
    communication_channel: null,
    country: null,
    customer_id: 413199,
    customer_name: "Jobin",
    dob: null,
    email: null,
    gender: "male",
    created_at: "2023-12-24",
    last_visited_date: "2023-12-24",
    last_visited_store: {
      store_id: 47,
      store_name: "Blr Brewing Co -Kanakapura Rd",
    },
    last_spent_amount: 66500,
    mobile_number: "9035499587",
    occupation: null,
    top_visited_store: {
      store_id: 47,
      store_name: "Blr Brewing Co -Kanakapura Rd",
    },
    total_spent: 66500,
    visits_count: 1,
    whatsapp_number: "9035499587",
    total_loyalty_points: 665
  },
  {
    account_id: 32,
    address1: null,
    address2: null,
    area: null,
    city: null,
    communication_channel: null,
    country: null,
    customer_id: 533134,
    customer_name: "Vaibhav",
    dob: null,
    email: null,
    gender: "male",
    created_at: "2024-01-07",
    last_visited_date: "2024-01-07",
    last_visited_store: {
      store_id: 47,
      store_name: "Blr Brewing Co -Kanakapura Rd",
    },
    last_spent_amount: 99000,
    mobile_number: "9163120036",
    occupation: null,
    top_visited_store: {
      store_id: 47,
      store_name: "Blr Brewing Co -Kanakapura Rd",
    },
    total_spent: 99000,
    visits_count: 1,
    whatsapp_number: "9163120036",
    total_loyalty_points: 990
  },
  {
    account_id: 32,
    address1: null,
    address2: null,
    area: null,
    city: null,
    communication_channel: null,
    country: null,
    customer_id: 511820,
    customer_name: "Saumya",
    dob: null,
    email: null,
    gender: "female",
    created_at: "2024-01-21",
    last_visited_date: "2024-01-20",
    last_visited_store: {
      store_id: 47,
      store_name: "Blr Brewing Co -Kanakapura Rd",
    },
    last_spent_amount: 95500,
    mobile_number: "9620162538",
    occupation: null,
    top_visited_store: {
      store_id: 47,
      store_name: "Blr Brewing Co -Kanakapura Rd",
    },
    total_spent: 95500,
    visits_count: 1,
    whatsapp_number: "9620162538",
    total_loyalty_points: 955
  },
  {
    account_id: 32,
    address1: null,
    address2: null,
    area: null,
    city: null,
    communication_channel: null,
    country: null,
    customer_id: 555629,
    customer_name: "Veena",
    dob: null,
    email: null,
    gender: "female",
    created_at: "2024-01-25",
    last_visited_date: "2024-01-25",
    last_visited_store: {
      store_id: 47,
      store_name: "Blr Brewing Co -Kanakapura Rd",
    },
    last_spent_amount: 41500,
    mobile_number: "9901242334",
    occupation: null,
    top_visited_store: {
      store_id: 47,
      store_name: "Blr Brewing Co -Kanakapura Rd",
    },
    total_spent: 41500,
    visits_count: 1,
    whatsapp_number: "9901242334",
    total_loyalty_points: 415
  },
  {
    account_id: 32,
    address1: null,
    address2: null,
    area: null,
    city: null,
    communication_channel: null,
    country: null,
    customer_id: 469752,
    customer_name: "Jeevan",
    dob: null,
    email: null,
    gender: "male",
    created_at: "2023-12-11",
    last_visited_date: "2023-12-11",
    last_visited_store: {
      store_id: 48,
      store_name: "Blr Brewing Co - Electronic City",
    },
    last_spent_amount: 79000,
    mobile_number: "9344434442",
    occupation: null,
    top_visited_store: {
      store_id: 48,
      store_name: "Blr Brewing Co - Electronic City",
    },
    total_spent: 79000,
    visits_count: 1,
    whatsapp_number: "9344434442",
    total_loyalty_points: 790
  },
];

module.exports = customerData;
