//************applicable customers*************
// 1 - all customers
// 2 - specific customers
//**************offer type*********************
// 1 - Percentage discount
// 2 - price discount
// 3 - Free item
// 4 - Buy 1 get 1
// 5 - Buy 1 get 2
// 6 - one for one
// 7 - one for two


const offers = [
  {
    title: "Special Hour Sale! ",
    description: "20% off on any beer on minimum spend of Rs 2999",
    start_date: "2024-04-13",
    end_date: "2024-07-31",
    applicable_customers: 1,
    customers: null,
    applicable_count: 1,
    is_loyalty_redeemable: false,
    minimum_purchase: 2999,
    offer_type: 1,
    start_time: "16:00",
    end_time: "20:00",
    discount_percentage: { discount: 20, maximum_amount: null },
    discount_price: null,
    free_items: null,
    buy_one_get_one: null,
    buy_two_get_one: null,
    one_for_one: null,
    one_for_two: null,
  },
  {
    title: "Hurry Sale! ",
    description: "Taste the chicken on your grab with 50% off",
    start_date: "2024-04-13",
    end_date: "2024-07-31",
    applicable_customers: 1,
    customers: null,
    applicable_count: 1,
    is_loyalty_redeemable: false,
    minimum_purchase: null,
    offer_type: 1,
    start_time: "16:00",
    end_time: "20:00",
    discount_percentage: { discount: 50, maximum_amount: null },
    discount_price: null,
    free_items: null,
    buy_one_get_one: null,
    buy_two_get_one: null,
    one_for_one: null,
    one_for_two: null,
  },
  {
    title: "Mid Night sale!",
    description: "Rs 500 off on any beer on minimum spend of Rs 2000",
    start_date: "2024-04-13",
    end_date: "2024-07-31",
    applicable_customers: 1,
    customers: null,
    applicable_count: 2,
    is_loyalty_redeemable: false,
    minimum_purchase: 2000,
    offer_type: 2, // price discount
    start_time: "16:00",
    end_time: "20:00",
    discount_percentage: null,
    discount_price: 500,
    free_items: null,
    buy_one_get_one: null,
    buy_two_get_one: null,
    one_for_one: null,
    one_for_two: null,
  },
  {
    title: "Summer Specials",
    description: "Summer sale offer",
    start_date: "2024-05-13",
    end_date: "2024-05-31",
    applicable_customers: 1,
    customers: null,
    applicable_count: 1,
    is_loyalty_redeemable: false,
    minimum_purchase: 1000,
    offer_type: 3,
    start_time: "14:00",
    end_time: "18:00",
    discount_percentage: null,
    discount_price: null,
    free_items: [15792, 15501, 60225],
    buy_one_get_one: null,
    buy_two_get_one: null,
    one_for_one: null,
    one_for_two: null,
  },
  {
    title: "BOGO",
    description: "Buy one Get one offers! Avail soon...",
    start_date: "2024-06-01",
    end_date: "2024-06-31",
    applicable_customers: 1,
    customers: null,
    applicable_count: 2,
    is_loyalty_redeemable: false,
    minimum_purchase: null,
    offer_type: 4,
    start_time: "14:00",
    end_time: "18:00",
    discount_percentage: {},
    discount_price: null,
    free_items: null,
    buy_one_get_one: [15792],
    buy_two_get_one: null,
    one_for_one: null,
    one_for_two: null,
  },
  {
    title: "Get Two Beer and chill with free Beer",
    description: "Buy two get one offer sale! avail soon!...",
    start_date: "2024-04-20",
    end_date: "2024-05-27",
    applicable_customers: 1,
    customers: null,
    applicable_count: 1,
    is_loyalty_redeemable: false,
    minimum_purchase: null,
    offer_type: 5,
    start_time: "14:00",
    end_time: "18:00",
    discount_percentage: null,
    discount_price: null,
    free_items: [15792, 15501, 60225],
    free_items: null,
    buy_one_get_one: null,
    buy_two_get_one: [15792],
    one_for_one: null,
    one_for_two: null,
  },
  {
    title: "IPL Fever",
    description: "ipl fever starts",
    start_date: "2024-04-20",
    end_date: "2024-05-27",
    applicable_customers: 1,
    customers: null,
    applicable_count: 1,
    is_loyalty_redeemable: false,
    minimum_purchase: null,
    offer_type: 6,
    start_time: "14:00",
    end_time: "18:00",
    discount_percentage: null,
    discount_price: null,
    free_items: [15792, 15501, 60225],
    free_items: null,
    buy_one_get_one: null,
    buy_two_get_one: null,
    one_for_one: {
      buy_item: 15501,
      free_item: 24966,
    },
    one_for_two: null,
  },
  {
    title: "Buy 2 cheesy burger and get Finger fries Free!",
    description:
      "Buy 2 cheesy burger and get Finger fries Free! Buy 2 get 1 freeee",
    start_date: "2024-04-20",
    end_date: "2024-05-27",
    applicable_customers: 1,
    customers: null,
    applicable_count: 1,
    is_loyalty_redeemable: false,
    minimum_purchase: null,
    offer_type: 7,
    start_time: "10:00",
    end_time: "12:00",
    discount_percentage: null,
    discount_price: null,
    free_items: null,
    free_items: null,
    buy_one_get_one: null,
    buy_two_get_one: null,
    one_for_one: null,
    one_for_two: {
      buy_item: 15819,
      free_item: 15820,
    },
  },
  {
    title: "Long Time no see",
    description: "Customers who have not visited(particular customers",
    start_date: "2024-03-17",
    end_date: "2024-05-17",
    applicable_customers: 2,
    customers: [395560, 396591, 397711],
    applicable_count: 2,
    is_loyalty_redeemable: false,
    minimum_purchase: 2999,
    offer_type: 2,
    start_time: "16:00",
    end_time: "20:00",
    discount_percentage: null,
    discount_price: 999,
    free_items: null,
    buy_one_get_one: null,
    buy_two_get_one: null,
    one_for_one: null,
    one_for_two: null,
  },
];

module.exports = offers;
